### PR TITLE
Support multiple python versions

### PR DESCRIPTION
**Pull request by rasjani**
Runs on
- python 2.7
- python 3.6

py34 fails for some setuptools issue and pythonnet doesnt seem to work on 3.7 - fix should be in but doesnt look like its released ..  scaling down to 2.7 & 3.6 for now.

### CODE REVIEW

**Comment by rasjani** [comment]
good to go from my side ..

**Comment by eeter** [comment]
This is very nice! Just one question about the twine task, if the build fails on 2.7 and succeeds on 3.6, will the package be published or not?

**Comment by rasjani** [comment]
> This is very nice! Just one question about the twine task, if the build fails on 2.7 and succeeds on 3.6, will the package be published or not?

Depends ..  Currently 2.6 and 3.6 are separate jobs and they are separately evaluted. IF 3.6 reach release stage and has been succeeding so far, release will be made. Job dependencies could be used to  to run 2.7 build first and then only 3.6 if that succeeds..

**Comment by eeter** [comment]
> eg, current 3.6 should store the build artifact of the wheel build and twine auth and publish then made into its own job, that fetches the artifact and then do a build if all previous jobs have passed.

This sounds like a good idea to me, since it would ensure that the released packages work with the versions that are supposed to be supported.

**Comment by rasjani** [comment]
PR re-opened - release job is now a dependency of white_py27 & white_py36 and if either of them should fail, release would not happen .. Hopefully.

**Pull request merged**
