### PR TITLE
Update release tasks in build pipeline

### LINKED ISSUE #61: Use proper way to generate build artifacts for release
Current CI uses https://github.com/Omenia/robotframework-whitelibrary/blob/master/deploy.cmd to make build artifacts that are then released via release task in azure.

Build artifacts should be made via "setup.py" .. for example calling `python setup.py sdist` and the collecting the zip file from dist/ folder ..

### LINKED ISSUE #108: Deprecated PyPI Publisher task fails in release
Modify to use: https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=azure-devops&tabs=designer

### PR DESCRIPTION
**Pull request by eeter**
- Release now uses twine in instead of the deprecated PyPI Publisher task. Release is done in build pipeline instead of release pipeline (missing YAML support).

- Releases .zip and universal .whl. 

Fixes #108 and closes #61

### CODE REVIEW

**Comment by rasjani** [comment]
Code looks perfect. However, there's a small "gotcha".

Twine upload and package generations are now configured to start if the build so far has succeeded and source branch is master. This would mean that every build that gets triggered from master would then try to upload to pypi. Eg, if pull request gets merged, a build will be triggered.

Now, since the version number wont get updated for each build, every build that *does not have* a version number that does not exist in the pypi servers would end up in a build failure since publishing a package with existing version number will do that - alteast when manually uploading a package.

Maybe the condition could also check if Build.Reason is "Manual" ?

No other issues atleast by visual inspection of the changes..

**Comment by eeter** [comment]
@rasjani The release pipeline that was used before was also triggered from master, creating pre-release versions for these "unstable" releases, e.g. "1.3.0.20190227.18rc0". The version number is set in the setup.py script, it's generated from the build number (that should be unique?). 

I didn't make changes to the versioning, but of course if there is a better way to do it we can update it. I tried publishing the packages to test PyPI on commits to this feature branch, and the pre-release versions were published successfully: https://pypi.org/project/robotframework-whitelibrary/#history 

Another thing I was wondering was if the deploy script and running it in the pipeline are needed anymore. I'm not that familiar with it but apart from copying dependencies to the library package (which could be moved to a separate task), running it looks unnecessary to me.

**Comment by eeter** [comment]
Replying to myself, the deploy script is no longer necessary and has now been removed :)

**Comment by rasjani** [comment]
> Replying to myself, the deploy script is no longer necessary and has now been removed :)

main issue with the deploy script was to deprecate it.. If everything else works as intended - ++ for the pr.

**Pull request merged**
